#!/bin/sh
cd insituBloodFlow

INSTALLDIR="$PWD/install"
BUILDDIR="$PWD/build"
SRCDIR="$PWD/src"
BASEDIR=$PWD

# echo "\ncurrent directory is:" $PWD
# echo "\nsetting ParaView install options:"
# # cmake -B $BUILDDIR/paraview -S $SRCDIR/paraview -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$INSTALLDIR/paraview -DPARAVIEW_INSTALL_DEVELOPMENT_FILES=ON -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DPARAVIEW_USE_PYTHON=ON -DPARAVIEW_USE_MPI=ON -DENABLE_CATALYST=ON -DENABLE_VTKM=ON  -DPARAVIEW_USE_QT=OFF -DVTK_SMP_IMPLEMENTATION_TYPE=TBB -DPARAVIEW_BUILD_EDITION=CATALYST_RENDERING -DVTK_USE_X=OFF -DVTK_OPENGL_HAS_OSMESA=ON -DOSMESA_INCLUDE_DIR=/usr/include/GL/ -DOSMESA_LIBRARY=/usr/lib/x86_64-linux-gnu/libOSMesa.so

# cmake -B $BUILDDIR/paraview -S $SRCDIR/paraview -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$INSTALLDIR/paraview -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DPARAVIEW_USE_PYTHON=ON -DPARAVIEW_USE_MPI=ON -DPARAVIEW_USE_QT=OFF -DVTK_SMP_IMPLEMENTATION_TYPE=TBB -DPARAVIEW_BUILD_EDITION=CATALYST_RENDERING -DVTK_USE_X=OFF -DVTK_OPENGL_HAS_OSMESA=ON -DOSMESA_INCLUDE_DIR=/usr/include/GL/ -DOSMESA_LIBRARY=/usr/lib/x86_64-linux-gnu/libOSMesa.so

# echo "\nchanging directory to build/paraview"
# cd $BUILDDIR/paraview
# echo "installing ParaView"
# make -j8
# make -j8 install
# echo "\ndone installing ParaView"




cmake -S  $SRCDIR/SENSEI -B $BUILDDIR/sensei -DCMAKE_INSTALL_PREFIX=$INSTALLDIR/sensei -DParaView_DIR=$INSTALLDIR/paraview/lib/cmake/paraview-5.10 -DENABLE_PYTHON=ON -DENABLE_CATALYST_PYTHON=ON -DENABLE_CATALYST=ON -DENABLE_VTK_IO=ON -DENABLE_LAMMPS=OFF -DENABLE_MANDELBROT=OFF -DENABLE_OSCILLATORS=ON -DENABLE_SINGLECELL=ON -DENABLE_ADIOS2=OFF -DADIOS2_DIR=$INSTALLDIR/ADIOS2/lib/cmake/adios2 
echo "changing directory to build/SENSEI"
cd $BUILDDIR/sensei
echo "installing SENSEI"
make -j8 
make -j8 install
