set(PALABOS_ROOT "/home/tishn/myFork/insituBloodFlow/src/palabos/" CACHE STRING "")
set(BLOODFLOW_ROOT "/home/tishn/myFork/insituBloodFlow/BloodFlow" CACHE STRING "")
set(LAMMPS_DIR "/home/tishn/myFork/insituBloodFlow/src/lammps/" CACHE STRING "")
#set(SENSEI_DIR "/home/jifutan/insituBloodFlow/install/SENSEI/lib/cmake" CACHE STRING "")
set(CMAKE_C_COMPILER "mpicc" CACHE STRING "Specify the compiler to use")
set(CMAKE_CXX_STANDARD "11" CACHE STRING "Using c++11 version")
